### ISSUE TITLE
Красивое перечисление игроков

### ISSUE THREAD

**Issue by Kiruha01** [Kiruha01/telegram-king#2]
Я имею такой код
```python 
# app.py - 72:73
players = database.get_players(message.from_user.id)
bot.send_message(message.from_user.id, f"Сегоднящние игроки - {}")
```
`players` - список объектов типа `Player`, объявленных в файле **logic/db_setup.py**

Мне хотелось бы вывести строку, в которой идёт перечисление имён игроков, записанных в `player.name'

**Comment by GrigorevGrigorii** [comment]
Попробуй это

![2AF0F284-F147-4D33-ABD1-25BB5D39C7CA](https://user-images.githubusercontent.com/55593191/112429624-f2c61c80-8d4d-11eb-80fd-92cf64584ba1.jpeg)

**Comment by Kiruha01** [comment]
С помощью `with_entities()` я действительно получаю только имена игроков. Но они дополнительно помещены в кортеж:
```python
[('Robert',), ('Daniel',), ('Faust',)]
```
Таким образом, я не могу использовать конструкцию
```python
", ".join(players)
```

**Comment by Kiruha01** [comment]
Я пожалуй остановлюсь на простом решении 
```python 
", ".join([i.name for i in players])
```
