### ISSUE TITLE
Проблема MySQL при редактировании записей

### ISSUE THREAD

**Issue by Kiruha01** [Kiruha01/telegram-king#3]
Когда я хочу изменить какую-то запись в базе данных, я сначала получаю эту запись
```python
obj = session.query(Obj).filter().one()
```
Далее произвожу изменения
```python
obj.name = "Robert"
obj.age = 20
```
И обновляю её в базе 
```python
session.add(obj)
session.commit()
```

При использовании SQLite всё идёт хорошо. Но на MySQL появляются исключения:
```
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: 'charmap' codec can't encode characters in position 0-5: character maps to <undefined> (Background on this error at: http://sqlalche.me/e/14/7s2a)
```

**Comment by Bezzzub** [comment]
Попробуй метод Update [https://docs.sqlalchemy.org/en/14/core/dml.html#sqlalchemy.sql.expression.update](url).

**Comment by Kiruha01** [comment]
**Проблема решена.**

При использовании ORM, после выполнения запросов
```python
user = session.query(User).first()
user.name = "Bob" 
````
sqlalchemy помещает этот объект в список на изменение. Для применения изменений нужно всего лишь
```python 
session.commit() 
```
